[2025-03-04T00:20:13.571+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T00:20:13.576+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_daily_load.cleanup_old_data scheduled__2025-03-03T00:00:00+00:00 [queued]>
[2025-03-04T00:20:13.579+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_daily_load.cleanup_old_data scheduled__2025-03-03T00:00:00+00:00 [queued]>
[2025-03-04T00:20:13.579+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-04T00:20:13.582+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): cleanup_old_data> on 2025-03-03 00:00:00+00:00
[2025-03-04T00:20:13.587+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=21959) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-04T00:20:13.586+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_price_daily_load', 'cleanup_old_data', 'scheduled__2025-03-03T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/daily_stock_price.py', '--cfg-path', '/tmp/tmpvxv0hpb4']
[2025-03-04T00:20:13.588+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask cleanup_old_data
[2025-03-04T00:20:13.588+0000] {standard_task_runner.py:72} INFO - Started process 21962 to run task
[2025-03-04T00:20:13.604+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_price_daily_load.cleanup_old_data scheduled__2025-03-03T00:00:00+00:00 [running]> on host 1d1d19bba66e
[2025-03-04T00:20:13.631+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_daily_load' AIRFLOW_CTX_TASK_ID='cleanup_old_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T00:00:00+00:00'
[2025-03-04T00:20:13.632+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-04T00:20:13.637+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-03-04T00:20:13.637+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-04T00:20:13.637+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-04T00:20:14.112+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-04T00:20:15.037+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-04T00:20:15.039+0000] {logging_mixin.py:190} INFO - âœ… Cleaned up rows so that only the last 180 trading days remain for each symbol.
[2025-03-04T00:20:15.040+0000] {connection.py:788} INFO - closed
[2025-03-04T00:20:15.189+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-03-04T00:20:15.356+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-04T00:20:15.372+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-04T00:20:15.373+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_price_daily_load, task_id=cleanup_old_data, run_id=scheduled__2025-03-03T00:00:00+00:00, execution_date=20250303T000000, start_date=20250304T002013, end_date=20250304T002015
[2025-03-04T00:20:15.412+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T00:20:15.424+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T00:20:15.425+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
