[2025-03-05T00:13:51.178+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T00:13:51.186+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_daily_load.fetch_and_load_data scheduled__2025-03-04T00:00:00+00:00 [queued]>
[2025-03-05T00:13:51.189+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_daily_load.fetch_and_load_data scheduled__2025-03-04T00:00:00+00:00 [queued]>
[2025-03-05T00:13:51.189+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-05T00:13:51.193+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): fetch_and_load_data> on 2025-03-04 00:00:00+00:00
[2025-03-05T00:13:51.199+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=44707) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T00:13:51.199+0000] {standard_task_runner.py:72} INFO - Started process 44718 to run task
[2025-03-05T00:13:51.198+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_price_daily_load', 'fetch_and_load_data', 'scheduled__2025-03-04T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/daily_stock_price.py', '--cfg-path', '/tmp/tmpvzqsz4oe']
[2025-03-05T00:13:51.200+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask fetch_and_load_data
[2025-03-05T00:13:51.227+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_price_daily_load.fetch_and_load_data scheduled__2025-03-04T00:00:00+00:00 [running]> on host 1d1d19bba66e
[2025-03-05T00:13:51.269+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_daily_load' AIRFLOW_CTX_TASK_ID='fetch_and_load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-04T00:00:00+00:00'
[2025-03-05T00:13:51.269+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-05T00:13:51.276+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-03-05T00:13:51.277+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-05T00:13:51.280+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-05T00:13:53.784+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T00:13:53.786+0000] {logging_mixin.py:190} INFO - YF.download() has changed argument auto_adjust default to True
[2025-03-05T00:14:10.542+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T00:14:12.686+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T00:14:12.687+0000] {logging_mixin.py:190} INFO - ✅ Inserted 1 new rows for TSLA.
[2025-03-05T00:14:13.305+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T01:08:42.820+0000] {job.py:229} INFO - Heartbeat recovered after 3266.38 seconds
[2025-03-05T01:08:44.678+0000] {multi.py:181} ERROR - 
1 Failed download:
[2025-03-05T01:08:44.679+0000] {multi.py:194} ERROR - ['SPY']: ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Read timed out. (read timeout=10)"))
[2025-03-05T01:08:44.686+0000] {logging_mixin.py:190} INFO - ✅ SPY: No new data from yfinance (df is empty).
[2025-03-05T01:08:44.686+0000] {connection.py:788} INFO - closed
[2025-03-05T01:08:46.204+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-03-05T01:08:46.269+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-05T01:08:46.276+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-05T01:08:46.277+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_price_daily_load, task_id=fetch_and_load_data, run_id=scheduled__2025-03-04T00:00:00+00:00, execution_date=20250304T000000, start_date=20250305T001351, end_date=20250305T010846
[2025-03-05T01:08:46.326+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T01:08:46.336+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-05T01:08:46.336+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
